sonar.projectKey=gorvshrma_Ecommerce
sonar.organization=gourvshrma

sonar.projectName=Cloud Native Ecommerce Platform

sonar.sources=app/backend/src,app/frontend/src
sonar.tests=app/backend/tests

sonar.python.coverage.reportPaths=app/backend/coverage.xml

sonar.exclusions=**/node_modules/**,**/dist/**,**/venv/**,**/__pycache__/**

sonar.sourceEncoding=UTF-8